### ISSUE TITLE
Segfault when running master on SITL

### ISSUE THREAD

**Issue by samuelctabor** [Microsoft/Frigatebird#1]
When running in SITL I get the following segfault:

 `Program received signal SIGSEGV, Segmentation fault.
0x00000000004ea483 in VarioSavitzkyGolayFilter::prediction (
    this=0x7d5c74 <plane+1236>, dt=2.85445094, 
    ekf_buffer=0x7d64b0 <plane+3344>, ekf_buffer_size=300, ekf_buffer_ptr=0, 
    Edot=0x7d6488 <plane+3304>, Edotdot=0x7d648c <plane+3308>)
    at ../../libraries/AP_Soaring/VarioSavitzkyGolayFilter.cpp:22
22              p1 += SG_FILTER_C[0][i] * ekf_buffer[k][0];`

My gcc version is 5.4.0 20160609. The only change I have made is to comment out the soaring-specific mavlink messages.

**Comment by iainguilliard** [comment]
Thanks for finding this Sam. I've pushed a fix: 773a259e93fd1305bcc8c678c1c7ff527b071f0d

**Comment by akolobov** [comment]
@iainguilliard fixed this one a while ago.
