### ISSUE TITLE
Mavlink message definitions missing

### ISSUE THREAD

**Issue by samuelctabor** [Microsoft/Frigatebird#2]
The soaring specific mavlink message definitions are missing from the repository. Please push the updated mavlink repository and update the submodule spec.

Many thanks.

**Comment by iainguilliard** [comment]
Copy the file Frigatebird/ardupilotmega.xml, in the root of the repository, over the one in the mavlink submodule: mavlink/message_definitions/v1.0/ardupilotmega.xml.
We did it this way for now, as we didn't want to bother with forking the mavlink module or pushing our unofficial changes to the message definitions.
This important step is missing from the BUILD.md notes.

**Comment by samuelctabor** [comment]
Thanks, I'll give that a go. How are you processing the messages on the ground, do you have a custom GCS?

**Comment by akolobov** [comment]
The build script has been modified compared to ArduPlane master to copy Frigatebird/ardupilotmega.xml from the repo root, which contains all the relevant message definitions, to mavlink/message_definitions/v1.0/ before building ArduPlane when you run "make px4-v2" from the ArduPlane directory. Does the copy fail when you build Frigatebird?

Thanks,


Andrey

**Comment by samuelctabor** [comment]
Hi Andrey,

Thanks, I was using waf, it does work using make.

Sam
